services:
  database:
    container_name: "postgres_dev"
    image: "postgres:16-alpine3.20"
    env_file:
      - ../.env.development
    environment:
      POSTGRES_PASSWORD: "local_password"
    ports:
      - "5432:5432"
